# Generated by Django 5.2.3 on 2025-12-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
